FLASK_SECRET_KEY='secretkey'
FLASK_SQLALCHEMY_DATABASE_URI='sqlite:///database.db'

POSTGRES_DATABASE = 'userImage'
POSTGRES_USER='postgres'
POSTGRES_PASSWORD='postgres'
POSTGRES_HOST='localhost'
POSTGRES_PORT='5432'

S3_ACCESS_KEY='AKIAQR5EO6LAQE4SFIWR'
S3_SECRET_KEY='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'
S3_BUCKET_NAME='flask-image-bucket'
S3_REGION='eu-north-1'